/**
 * Problem 2:
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 */

var fibArray = [1, 2];
var evenArray = [];
var total = 0;

function isEven(x) {
    if (x % 2 === 0) {
        return true;
    } else {
        return false;
    }
}

for (var i = 2; fibArray[i-1] < 4000000; i++) {
    fibArray[i] = fibArray[i-2] + fibArray[i-1];
}

for (var j = 0; j < fibArray.length; j++) {
    if (isEven(fibArray[j])) {
        evenArray.push(fibArray[j]);
    }
}

for (var k = 0; k < evenArray.length; k++) {
    total += evenArray[k];
}

console.log(total);